gText_Birch_Welcome::
	.string "yooooo what we saying\p"
	.string "Welcome to the gauntlet.\p"
	.string "My name is BIRCH and Mark couldn't be\p"
	.string "arsed to edit me out of the intro.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Look at this fuck ass pokemon I caught 5 mins ago”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "i'm just the goat or what\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\p"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "You're {PLAYER}{KUN} who will be attempting\n"
	.string "the gauntlet.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Good luck! You'll need it.\p"
	.string "$"
